Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Assignmentapp.urls')),
    path('studentpanel/', include('studentapp.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Assignmentapp/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False)

        if not username:
            raise ValueError('The Username must be set')
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self.create_user(username, password, **extra_fields)


class User(AbstractUser):
    gender = (
        ('1', 'Female'),
        ('2', 'Male'),
    )
    userrole = (
        ('1', 'Admin'),
        ('2', 'Teacher'),
        ('3', 'Student'),
    )
    first_name = None
    last_name = None
    user_full_name = models.CharField(max_length=100, null=True)
    user_mobile = models.IntegerField(null=True)
    user_address = models.TextField(verbose_name='Address', blank=True, null=True)
    user_image = models.ImageField(blank=True, null=True, upload_to='profileimages/', )
    user_gender = models.CharField(verbose_name='Gender', max_length=20, choices=gender, default='1',
                                   blank=True, null=True)
    user_role = models.CharField(verbose_name='User Role', max_length=20, choices=userrole, default='1',
                                 blank=True, null=True)
    user_dob = models.DateField(verbose_name='Date of Birth', blank=True, null=True)
    objects = UserManager()

    class Meta:
        verbose_name_plural = 'Users'

    def _str_(self):
        return self.username


class Department(models.Model):
    dept_name = models.CharField(verbose_name='Department Name', max_length=40)
    teacher_count = models.IntegerField(blank=True, null=True)
    student_count = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Departments'

    def __str__(self):
        return self.dept_name


class Semester(models.Model):
    dept = models.ForeignKey(Department, models.SET_NULL, verbose_name='Department Name',
                             blank=True, null=True)
    sem_no = models.IntegerField()
    sub_count = models.IntegerField(blank=True, null=True)

    def __str__(self):
        dep = str(self.sem_no)
        return dep


class Subject(models.Model):
    dept = models.ForeignKey(Department, models.SET_NULL, verbose_name='Department Name',
                             blank=True, null=True)
    semref = models.ForeignKey(Semester, models.SET_NULL, verbose_name='Semester No',
                               blank=True, null=True)
    sub_name = models.CharField(verbose_name='Subject Name', max_length=40)

    def __str__(self):
        return self.sub_name


class Teacher(models.Model):
    user_ref = models.ForeignKey(User, models.SET_NULL, verbose_name='User Details', related_name='user_reference',
                                 blank=True, null=True)
    dept = models.ManyToManyField(Department, related_name='teacher_dept')
    semref = models.ManyToManyField(Semester, verbose_name='Semester No')
    subref = models.ManyToManyField(Subject, verbose_name='Subject Details')

    def __str__(self):
        return self.user_ref.username


class Student(models.Model):
    user_ref = models.ForeignKey(User, models.SET_NULL, verbose_name='User Details', related_name='user_reference2',
                                 blank=True, null=True)
    stud_roll = models.IntegerField(verbose_name='Student Roll No')
    dept = models.ForeignKey(Department, models.SET_NULL, verbose_name='Student Department',
                             blank=True, null=True)
    semref = models.ForeignKey(Semester, models.SET_NULL, verbose_name='Semester No',
                               blank=True, null=True)


class Assignments(models.Model):
    dept = models.ForeignKey(Department, models.SET_NULL, verbose_name='Department Name',
                             blank=True, null=True)
    semref = models.ForeignKey(Semester, models.SET_NULL, verbose_name='Semester No',
                               blank=True, null=True)
    subref = models.ForeignKey(Subject, models.SET_NULL, verbose_name='Subject Details', blank=True, null=True)
    teacher = models.ForeignKey(Teacher, models.SET_NULL, verbose_name='Teacher Details', blank=True, null=True)
    asg_no = models.IntegerField(verbose_name='Assignment No', blank=True, null=True)
    asg_title = models.CharField(verbose_name='Assignment Title', max_length=255)
    asg_file = models.FileField(upload_to='AssignmentFiles', blank=True, null=True)
    asg_createdtime = models.DateTimeField(auto_now_add=True)
    asg_deadline = models.DateTimeField()
    asg_marks = models.IntegerField(verbose_name='Marks', blank=True, null=True)


class Submission(models.Model):
    asgref = models.ForeignKey(Assignments, models.SET_NULL, verbose_name='Assignment Details',
                               related_name='assignment_ref', blank=True, null=True)
    studref = models.ForeignKey(Student, models.SET_NULL, verbose_name='Student Details', related_name='student_ref',
                                blank=True, null=True)
    submittime = models.DateTimeField(blank=True, null=True)
    submission_file = models.FileField(upload_to='SubmittedFiles', blank=True, null=True)
    submissionstatus = models.BooleanField(default=False)

Assignmentapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput, EmailInput, FileInput, PasswordInput

from Assignmentapp.models import User, Department, Student, Subject, Semester, Assignments, Teacher


class AddEditDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['dept_name']


class DeleteDepartmentForm(forms.Form):
    dept_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddEditSemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = ['dept', 'sem_no']


class DeleteSemesterForm(forms.Form):
    dept = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))
    sem_no = forms.IntegerField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddSubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['dept', 'semref', 'sub_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'semref' in self.data:
            self.fields['semref'].queryset = Semester.objects.all()


class EditSubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['dept', 'semref', 'sub_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['semref'].queryset = Semester.objects.none()

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            dept_id = self.instance.dept.id
            self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)


class DeleteSubjectForm(forms.Form):
    sub_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddTeacherForm(UserCreationForm):
    password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    username = forms.CharField()
    user_image = forms.ImageField(required=False, widget=FileInput(attrs={'class': 'form-control-file'}))
    user_role = forms.ChoiceField(required=False)

    def clean_username(self):
        vusername = self.cleaned_data['username']
        if ' ' in vusername:
            raise forms.ValidationError('Username should not contain any space')
        return vusername

    class Meta:
        model = User
        fields = ['username', 'user_full_name', 'email', 'user_mobile', 'user_image', 'password1',
                  'password2', 'user_address', 'user_gender', 'user_role', 'user_dob']
        widgets = {
            "username": TextInput(
                attrs={
                    "class": "form-control"
                }),

            "user_full_name": TextInput(
                attrs={
                    "class": "form-control"
                }),
            "email": EmailInput(
                attrs={
                    "class": "form-control",
                    "type": "email"
                }),
            "user_mobile": TextInput(
                attrs={
                    "class": "form-control"
                }),

        }

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'profileimages/user.png'
            return user_image


class AddTeacherDetailsForm(forms.Form):
    dept = forms.ModelChoiceField(queryset=Department.objects.all(), widget=forms.Select(attrs={'class': 'deptclass'}))
    semref = forms.ModelChoiceField(queryset=Semester.objects.all(), widget=forms.Select(attrs={'class': 'semclass'}))
    subref = forms.ModelChoiceField(queryset=Subject.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass

        if 'semref' in self.data:
            try:
                semref_id = int(self.data.get('semref'))
                self.fields['subref'].queryset = Subject.objects.filter(semref__id=semref_id)
            except (ValueError, TypeError):
                pass


class EditTeacherForm(UserChangeForm):
    password = None
    dept = forms.ModelMultipleChoiceField(label='Departments',
                                          queryset=Department.objects.all(),
                                          widget=forms.CheckboxSelectMultiple
                                          )

    class Meta:
        model = User
        fields = ['user_full_name', 'email', 'user_mobile', 'user_image', 'user_address', 'user_gender', 'user_dob']

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'emptyimage'
            return user_image


class DeleteTeacherForm(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddStudentForm(UserCreationForm):
    password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    username = forms.CharField()
    user_image = forms.ImageField(required=False, widget=FileInput(attrs={'class': 'form-control-file'}))
    dept = forms.ModelChoiceField(label='Departments',
                                  queryset=Department.objects.all(),
                                  widget=forms.Select()
                                  )
    semref = forms.ModelChoiceField(label='Semester',
                                    queryset=Semester.objects.none(),
                                    widget=forms.Select()
                                    )
    user_role = forms.ChoiceField(required=False)
    stud_roll = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'semref' in self.data:
            self.fields['semref'].queryset = Semester.objects.all()

    def clean_username(self):
        vusername = self.cleaned_data['username']
        if ' ' in vusername:
            raise forms.ValidationError('Username should not contain any space')
        return vusername

    def clean_stud_roll(self):
        vstudroll = self.cleaned_data['stud_roll']
        vstuddept = self.cleaned_data['dept']
        studentObj = Student.objects.filter(stud_roll=vstudroll, dept=vstuddept)
        if studentObj:
            raise forms.ValidationError('Roll No already Exists')
        else:
            return vstudroll

    class Meta:
        model = User
        fields = ['username', 'user_full_name', 'email', 'user_mobile', 'user_image', 'password1',
                  'password2', 'user_address', 'user_gender', 'user_role', 'user_dob']
        widgets = {
            "username": TextInput(
                attrs={
                    "class": "form-control"
                }),

            "user_full_name": TextInput(
                attrs={
                    "class": "form-control"
                }),
            "email": EmailInput(
                attrs={
                    "class": "form-control",
                    "type": "email"
                }),
            "user_mobile": TextInput(
                attrs={
                    "class": "form-control"
                }),

        }

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'profileimages/user.png'
            return user_image


class EditStudentForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['user_full_name', 'email', 'user_mobile', 'user_image', 'user_address', 'user_gender', 'user_dob']

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'emptyimage'
            return user_image


class EditStudentDetailsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('stud_roll', 'dept', 'semref')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['semref'].queryset = Semester.objects.none()

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            dept_id = self.instance.dept.id
            self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)


class DeleteStudentForm(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddAssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignments
        fields = ('dept', 'semref', 'subref', 'teacher', 'asg_no', 'asg_title', 'asg_file', 'asg_deadline', 'asg_marks')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user.user_role == '2':
            teacherObj = Teacher.objects.get(user_ref__id=self.user.id)
            self.fields['dept'].queryset = Department.objects.filter(id__in=teacherObj.dept.all())

templates/student/addstudent.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Add Student</h1>
        <form method="POST" enctype="multipart/form-data" id="semesterForm" data-sem-url="{% url 'ajax_load_sem' %}">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <button type="submit">Add</button>
            <a href="{% url 'student' %}">Cancel</a>
        </form>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $( document ).ready(function() {
                $("#id_dept").change(function () {
                var url = $("#semesterForm").attr("data-sem-url");
                var deptId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'dept': deptId
                    },
                    success: function (data) {
                    $("#id_semref").html(data);
                    }
                });
                });
            });
        </script>

    </div>
</div>
{% endblock %}

templates/student/deletestudent.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Delete Student</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}

            <button name="submit" type="submit">Delete</button>
            <a href="{% url 'student' %}">Cancel</a>
        </form>

    </div>
</div>
{% endblock %}

templates/student/editstudent.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Edit Student</h1>
        <form method="POST" enctype="multipart/form-data" id="semesterForm" data-sem-url="{% url 'ajax_load_sem' %}">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                {{ form2.as_table }}
            </table>
            <button name="submit" type="submit">Update</button>
        </form>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $( document ).ready(function() {
                $("#id_dept").change(function () {
                var url = $("#semesterForm").attr("data-sem-url");
                var deptId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'dept': deptId
                    },
                    success: function (data) {
                    $("#id_semref").html(data);
                    }
                });
                });
            });
        </script>
    </div>
</div>
{% endblock %}

templates/student/sem_options.html
<option value="">---------</option>
{% for semester in semesters %}
<option value="{{ semester.id }}">{{ semester.sem_no }}</option>
{% endfor %}

templates/student/student.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <a href="{% url 'addstudent' %}">Add</a>
    </div>
    <div class="row">
        <div class="col-12 col-m-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Students
                    </h2>
                </div>
                <div class="card-content">
                    <table>
                        <thead>
                        <tr>
                            <th>Roll No</th>
                            <th>Username</th>
                            <th>Name</th>
                            <th>DOB</th>
                            <th>Gender</th>
                            <th>Department</th>
                            <th>Semester</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{{student.stud_roll}}</td>
                            <td>{{student.user_ref.username}}</td>
                            <td>{{student.user_ref.user_full_name}}</td>
                            <td>{{student.user_ref.user_dob}}</td>
                            <td>{{student.user_ref.get_user_gender_display}}</td>
                            <td>{{student.dept.dept_name}}</td>
                            <td>{{student.semref.sem_no}}</td>
                            <td><a href="{% url 'editstudent' student.id %}">Edit</a></td>
                            <td><a href="{% url 'deletestudent' student.id %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}