Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Assignmentapp.urls')),
    path('studentpanel/', include('studentapp.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Assignmentapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput, EmailInput, FileInput, PasswordInput

from Assignmentapp.models import User, Department, Student, Subject, Semester, Assignments, Teacher


class AddEditDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['dept_name']


class DeleteDepartmentForm(forms.Form):
    dept_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddEditSemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = ['dept', 'sem_no']


class DeleteSemesterForm(forms.Form):
    dept = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))
    sem_no = forms.IntegerField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddSubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['dept', 'semref', 'sub_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'semref' in self.data:
            self.fields['semref'].queryset = Semester.objects.all()


class EditSubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['dept', 'semref', 'sub_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['semref'].queryset = Semester.objects.none()

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            dept_id = self.instance.dept.id
            self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)


class DeleteSubjectForm(forms.Form):
    sub_name = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddTeacherForm(UserCreationForm):
    password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    username = forms.CharField()
    user_image = forms.ImageField(required=False, widget=FileInput(attrs={'class': 'form-control-file'}))
    user_role = forms.ChoiceField(required=False)

    def clean_username(self):
        vusername = self.cleaned_data['username']
        if ' ' in vusername:
            raise forms.ValidationError('Username should not contain any space')
        return vusername

    class Meta:
        model = User
        fields = ['username', 'user_full_name', 'email', 'user_mobile', 'user_image', 'password1',
                  'password2', 'user_address', 'user_gender', 'user_role', 'user_dob']
        widgets = {
            "username": TextInput(
                attrs={
                    "class": "form-control"
                }),

            "user_full_name": TextInput(
                attrs={
                    "class": "form-control"
                }),
            "email": EmailInput(
                attrs={
                    "class": "form-control",
                    "type": "email"
                }),
            "user_mobile": TextInput(
                attrs={
                    "class": "form-control"
                }),

        }

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'profileimages/user.png'
            return user_image


class AddTeacherDetailsForm(forms.Form):
    dept = forms.ModelChoiceField(queryset=Department.objects.all(), widget=forms.Select(attrs={'class': 'deptclass'}))
    semref = forms.ModelChoiceField(queryset=Semester.objects.all(), widget=forms.Select(attrs={'class': 'semclass'}))
    subref = forms.ModelChoiceField(queryset=Subject.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass

        if 'semref' in self.data:
            try:
                semref_id = int(self.data.get('semref'))
                self.fields['subref'].queryset = Subject.objects.filter(semref__id=semref_id)
            except (ValueError, TypeError):
                pass


class EditTeacherForm(UserChangeForm):
    password = None
    dept = forms.ModelMultipleChoiceField(label='Departments',
                                          queryset=Department.objects.all(),
                                          widget=forms.CheckboxSelectMultiple
                                          )

    class Meta:
        model = User
        fields = ['user_full_name', 'email', 'user_mobile', 'user_image', 'user_address', 'user_gender', 'user_dob']

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'emptyimage'
            return user_image


class DeleteTeacherForm(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddStudentForm(UserCreationForm):
    password1 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    username = forms.CharField()
    user_image = forms.ImageField(required=False, widget=FileInput(attrs={'class': 'form-control-file'}))
    dept = forms.ModelChoiceField(label='Departments',
                                  queryset=Department.objects.all(),
                                  widget=forms.Select()
                                  )
    semref = forms.ModelChoiceField(label='Semester',
                                    queryset=Semester.objects.none(),
                                    widget=forms.Select()
                                    )
    user_role = forms.ChoiceField(required=False)
    stud_roll = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'semref' in self.data:
            self.fields['semref'].queryset = Semester.objects.all()

    def clean_username(self):
        vusername = self.cleaned_data['username']
        if ' ' in vusername:
            raise forms.ValidationError('Username should not contain any space')
        return vusername

    def clean_stud_roll(self):
        vstudroll = self.cleaned_data['stud_roll']
        vstuddept = self.cleaned_data['dept']
        studentObj = Student.objects.filter(stud_roll=vstudroll, dept=vstuddept)
        if studentObj:
            raise forms.ValidationError('Roll No already Exists')
        else:
            return vstudroll

    class Meta:
        model = User
        fields = ['username', 'user_full_name', 'email', 'user_mobile', 'user_image', 'password1',
                  'password2', 'user_address', 'user_gender', 'user_role', 'user_dob']
        widgets = {
            "username": TextInput(
                attrs={
                    "class": "form-control"
                }),

            "user_full_name": TextInput(
                attrs={
                    "class": "form-control"
                }),
            "email": EmailInput(
                attrs={
                    "class": "form-control",
                    "type": "email"
                }),
            "user_mobile": TextInput(
                attrs={
                    "class": "form-control"
                }),

        }

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'profileimages/user.png'
            return user_image


class EditStudentForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['user_full_name', 'email', 'user_mobile', 'user_image', 'user_address', 'user_gender', 'user_dob']

    def clean_user_image(self):
        user_image = self.cleaned_data['user_image']
        if user_image:
            return user_image
        else:
            user_image = 'emptyimage'
            return user_image


class EditStudentDetailsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('stud_roll', 'dept', 'semref')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['semref'].queryset = Semester.objects.none()

        if 'dept' in self.data:
            try:
                dept_id = int(self.data.get('dept'))
                self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            dept_id = self.instance.dept.id
            self.fields['semref'].queryset = Semester.objects.filter(dept__id=dept_id)


class DeleteStudentForm(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'readonly': True}))


class AddAssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignments
        fields = ('dept', 'semref', 'subref', 'teacher', 'asg_no', 'asg_title', 'asg_file', 'asg_deadline', 'asg_marks')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user.user_role == '2':
            teacherObj = Teacher.objects.get(user_ref__id=self.user.id)
            self.fields['dept'].queryset = Department.objects.filter(id__in=teacherObj.dept.all())

templates/assignment/addassignment.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Add Assignment</h1>
        <form method="post" enctype="multipart/form-data" id="assignmentForm" data-sem-url="{% url 'ajax_load_sem' %}"
              data-sub-url="{% url 'ajax_load_sub' %}">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Add</button>
            <a href="{% url 'student' %}">Cancel</a>
        </form>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $( document ).ready(function() {
                $("#id_dept").change(function () {
                var url = $("#assignmentForm").attr("data-sem-url");
                var deptId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'dept': deptId
                    },
                    success: function (data) {
                    $("#id_semref").html(data);
                    }
                });
                });

                $("#id_semref").change(function () {
                var url = $("#assignmentForm").attr("data-sub-url");
                var semrefId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'semref': semrefId
                    },
                    success: function (data) {
                    $("#id_subref").html(data);
                    }
                });
                });
            });

        </script>

    </div>
</div>
{% endblock %}

templates/assignment/assignment.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <a href="{% url 'addassignment' %}">Add</a><br>
    </div>
    <div class="row">
        <div class="col-12 col-m-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h2>
                        Assignments
                    </h2>
                </div>
                <div class="card-content">
                    <table>
                        <thead>
                        <tr>
                            <th>Assignment No</th>
                            <th>Assignment Title</th>
                            <th>Department Name</th>
                            <th>Semester</th>
                            <th>Subject Name</th>
                            <th>Deadline</th>
                            <th>Marks</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for assignment in assignments %}
                        <tr>
                            <td>{{assignment.asg_no}}</td>
                            <td>{{assignment.asg_title}}</td>
                            <td>{{assignment.dept.dept_name}}</td>
                            <td>{{assignment.semref.sem_no}}</td>
                            <td>{{assignment.subref.sub_name}}</td>
                            <td>{{assignment.asg_deadline}}</td>
                            <td>{{assignment.asg_marks}}</td>
                            <td><a href="{% url 'editassignment' assignment.id %}">Edit</a></td>
                            <td><a href="{% url 'deleteassignment' assignment.id %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/assignment/deleteassignment.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Delete Assignment</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}

            <button name="submit" type="submit">Delete</button>
            <a href="{% url 'assignment' %}">Cancel</a>
        </form>

    </div>
</div>
{% endblock %}

templates/assignment/editassignment.html
{% extends "base.html" %}

{% block bodycontent %}
<div class="wrapper">
    <div class="row">
        <h1>Edit Assignment</h1>
        <form method="POST" enctype="multipart/form-data"  id="assignmentForm" data-sem-url="{% url 'ajax_load_sem' %}"
              data-sub-url="{% url 'ajax_load_sub' %}">
            {% csrf_token %}
            {{form.as_p}}

            <button name="submit" type="submit">Update</button>
        </form>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $( document ).ready(function() {
                $("#id_dept").change(function () {
                var url = $("#assignmentForm").attr("data-sem-url");
                var deptId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'dept': deptId
                    },
                    success: function (data) {
                    $("#id_semref").html(data);
                    }
                });
                });

                $("#id_semref").change(function () {
                var url = $("#assignmentForm").attr("data-sub-url");
                var semrefId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                    'semref': semrefId
                    },
                    success: function (data) {
                    $("#id_subref").html(data);
                    }
                });
                });
            });

        </script>

    </div>
</div>
{% endblock %}

templates/assignment/sub_options.html
<option value="">---------</option>
{% for subject in subjects %}
<option value="{{ subject.id }}">{{ subject.sub_name }}</option>
{% endfor %}